### ISSUE TITLE
Magisk Parsing Error 1.28.3

### ISSUE THREAD

**Issue by CHEF-KOCH** [Magisk-Modules-Repo/Busybox-Installer#1]
The latest version (as for now) 1.28.3 gives me a parsing error. I'm not sure what is causing it, maybe the repo on XDA needs to be updated because it points to 1.28.2. 

I would be kind for you to fix the Magisk repo/release so that people could install the new version. 

Many thanks for all of the work here! 🥇

**Comment by osm0sis** [comment]
This doesn't make any sense. It installs fine.

**Comment by CHEF-KOCH** [comment]
Okay, thank you for confirmation. Seems then it's Magisk Manager related. 

* I tried to upgrade -> processing error
* Tried to uninstall / re-download -> parsing error.

Points out that when you delete old file in the /MagiskManager dir it works without issue. Seems something got wrong here. Strange thing is I could update other modules. 

I just mention it in case someone has same problems.
